# Generated by Django 5.2.9 on 2026-07-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Masala Tea', 'Masala Tea'), ('Ginger Tea', 'Ginger Tea'), ('Green Tea', 'Green Tea'), ('Lemon Tea', 'Lemon Tea'), ('Black Tea', 'Black Tea')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
