# Generated by Django 5.2.9 on 2026-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Masala Tea', 'Masala Tea'), ('Ginger Tea', 'Ginger Tea'), ('Green Tea', 'Green Tea'), ('Black Tea', 'Black Tea'), ('Milk Tea', 'Milk Tea'), ('Lemon Tea', 'Lemon Tea'), ('Osmania Biscuit', 'Osmania Biscuit'), ('Parle-G', 'Parle-G'), ('Good Day', 'Good Day'), ('Marie Gold', 'Marie Gold'), ('Cookies', 'Cookies')], max_length=50),
        ),
    ]
